# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('stage', models.CharField(default='basic_details', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'indexes': [models.Index(fields=['user_id', 'status'], name='sessions_user_id_status_idx'), models.Index(fields=['expires_at'], name='sessions_expires_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('stage', models.CharField(default='basic_details', max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('messages', models.JSONField(default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'stage'], name='conversations_user_id_stage_idx'), models.Index(fields=['session_id'], name='conversations_session_id_idx'), models.Index(fields=['created_at'], name='conversations_created_at_idx')],
            },
        ),
    ]
